[package]
name = "zeep"
version = "0.2.1"
authors = ["mibes <mibes@avaya.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
clap = "4"
zeep-lib = { path = "../zeep-lib" }
